### ISSUE TITLE
when we request the url using the browser  getting some error

### ISSUE THREAD

**Issue by sivatharan** [ad-tech-group/openssp#16]
#project is running
URL :
http://localhost:8080/open-ssp/SupplyVideoService?site=1&test=1

I am getting this error
ERROR: CoreSupplyServlet com.atg.openssp.core.cache.type.SiteDataCache cache empty for 1

**Comment by Ozyet** [comment]
Hi Andre,

I'm having the same issue in the project tag v0.2. I've noticed the following error messages in the tomcat console which refers the line 49 in AbstractConfigurationLoader.java file: final Set<Object> keys = properties.keySet();

Here is the console:

INFO: ApplicationInit **** Initing core application ****
INFO: ApplicationInit **** SSP Version: 0.2 ****
ERROR: AbstractConfigurationLoader null
Jul 09, 2018 8:19:23 PM org.apache.catalina.core.ApplicationContext log
SEVERE: StandardWrapper.Throwable
java.lang.NullPointerException 
at com...system.loader.AbstractConfigurationLoader.readValues(AbstractConfigurationLoader.java:49)
at com.atg.openssp.core.system.ApplicationInit.init(ApplicationInit.java:53)

Jul 09, 2018 8:19:23 PM org.apache.catalina.core.StandardContext loadOnStartup
SEVERE: Servlet /open-ssp threw load() exception
java.lang.NullPointerException
at com.atg...em.loader.AbstractConfigurationLoader.readValues(AbstractConfigurationLoader.java:49)
at com.atg.openssp.core.system.ApplicationInit.init(ApplicationInit.java:53)

When I send a request: http://localhost:8080/open-ssp/SupplyVideoService?site=1&test=1
The console message: ERROR: CoreSupplyServlet com.atg.openssp.core.cache.type.SiteDataCache cache empty for 1

Any idea about what goes wrong related to AbstractConfigurationLoader?

Thanks,
Ozyet.

**Comment by Ozyet** [comment]
+Additional info:
I'm running the platform in local environment and used the following command in core folder:
sudo mvn tomcat7:run-war

**Comment by schmermeister** [comment]
Ho all,

the problem occurs in ProjectProperty.readFile() method. In some cases it couldn't determined if OpenSSP runs on a dev environment or production. Fixed in version 0.3.

**Comment by Ozyet** [comment]
Hi Andre,

Thanks for your reply. I've just checked but couldn't find a tag for v0.3 in GitHub. Just wonder if you are planning to release this version here?

**Comment by schmermeister** [comment]
Hi,
you are right it is not tagged yet. The master branch ist v0.3.

**Comment by damai21** [comment]
hello man, how to create javascript ad tags?
